version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  checklint:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: npm run linter
workflows:
  node-tests:
    jobs:
      - node/test
      - checklint